[package]
name = "api"
version = "0.1.0"
authors = ["Nicholas Jorgenson"]
edition = "2018"

[dependencies]
actix-http = "3.0.0-beta.9"
actix-web = "4.0.0-beta.8"

sqlx = { version = "0.5.7", features = ["runtime-actix-native-tls", "macros", "postgres", "chrono", "migrate"] }

tracing = { version = "0.1.26", features = ["attributes"] }
tracing-log = "0.1.2"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.2.20", features = ["registry"] }
tracing-actix-web = "0.4.0-beta.11"

serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
config = "0.11.0"

[dev-dependencies]
reqwest = "0.11.4"

[lib]
path = "src/lib.rs"

[[bin]]
name = "api"
path = "src/main.rs"
